server:
  port: 8085

---

spring:
  profiles:
    default: local

  datasource:
    url: ${AZURE_MYSQL_SERVER_URL}
    username: ${AZURE_MYSQL_SERVER_USERNAME}
    password: ${AZURE_MYSQL_SERVER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

---
spring:
  mvc:
    cors:
      mappings:
        /api/*:
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true

---
spring:
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_S3_BUCKET_ACCESSKEY}
        secretKey: ${AWS_S3_BUCKET_SECRETKEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ${AWS_S3_BUCKET_REGION}

---


